"""Features engineering module for training metrics.

Modules:
- workload: ACWR, monotony, strain calculations
- cardio: TRIMP, HR zones, VO2max, efficiency
- strength: 1RM estimation, volume, intensity, VBT
- fitness: CTL/ATL/TSB (Banister model), readiness
- recommendations: Intelligent training advice
"""

# Workload metrics
# Cardio metrics
from arete.features.cardio import (
    CardioSession,
    HRZone,
    Sex,
    ZoneDistribution,
    calculate_aerobic_decoupling,
    calculate_cardiac_drift,
    calculate_efficiency_factor,
    calculate_gap,
    calculate_hr_ratio,
    calculate_trimp,
    calculate_trimp_simplified,
    calculate_zone_boundaries,
    estimate_hrmax_gulati,
    estimate_hrmax_tanaka,
    estimate_hrmax_traditional,
    estimate_vo2max_cooper,
    estimate_vo2max_hr,
    estimate_vo2max_running,
    format_pace,
    get_hr_zone,
    pace_to_speed,
    speed_to_pace,
)

# Fitness model (Banister)
from arete.features.fitness import (
    DailyTSS,
    FitnessMetrics,
    FormZone,
    PerformanceModel,
    ReadinessLevel,
    calculate_atl,
    calculate_ctl,
    calculate_fitness_metrics,
    calculate_ramp_rate,
    calculate_readiness_score,
    calculate_tsb,
    compute_performance_model,
    estimate_days_to_peak,
    get_form_zone,
    get_readiness_level,
    is_ramp_rate_safe,
    predict_performance,
    recommend_taper_duration,
    srpe_to_tss,
    strength_volume_to_tss,
    trimp_to_tss,
)

# Recommendations
from arete.features.recommendations import (
    Category,
    Priority,
    Recommendation,
    RecommendationReport,
    WeekPlan,
    generate_recommendations,
    generate_week_plan,
)

# Strength metrics
from arete.features.strength import (
    Exercise,
    ExerciseSet,
    StrengthSession,
    StrengthZone,
    VBTZone,
    calculate_average_intensity,
    calculate_e1rm_volume,
    calculate_inol,
    calculate_relative_intensity,
    calculate_session_inol,
    calculate_session_volume,
    calculate_strength_training_load,
    calculate_volume,
    estimate_1rm_average,
    estimate_1rm_brzycki,
    estimate_1rm_epley,
    estimate_1rm_from_velocity,
    estimate_1rm_lombardi,
    estimate_1rm_mayhew,
    estimate_1rm_oconner,
    estimate_1rm_rpe,
    get_strength_zone,
    get_vbt_zone,
    get_zone_boundaries,
    percentage_from_reps,
    velocity_target_for_percentage,
    weight_for_reps_at_percentage,
    weight_for_target_reps,
)
from arete.features.workload import (
    ACWRResult,
    ACWRZone,
    DailyLoad,
    MonotonyZone,
    StrainZone,
    WorkloadMetrics,
    calculate_acute_load,
    calculate_acwr,
    calculate_acwr_ewma,
    calculate_chronic_load,
    calculate_ewma_load,
    calculate_load_change_percent,
    calculate_monotony,
    calculate_strain,
    calculate_training_load,
    calculate_weekly_load,
    compute_workload_metrics,
    get_acwr_result,
    get_acwr_zone,
    get_monotony_zone,
    get_safe_load_increase,
    get_strain_zone,
)

__all__ = [
    # Workload
    "ACWRResult",
    "ACWRZone",
    "DailyLoad",
    "MonotonyZone",
    "StrainZone",
    "WorkloadMetrics",
    "calculate_acute_load",
    "calculate_acwr",
    "calculate_acwr_ewma",
    "calculate_chronic_load",
    "calculate_ewma_load",
    "calculate_load_change_percent",
    "calculate_monotony",
    "calculate_strain",
    "calculate_training_load",
    "calculate_weekly_load",
    "compute_workload_metrics",
    "get_acwr_result",
    "get_acwr_zone",
    "get_monotony_zone",
    "get_safe_load_increase",
    "get_strain_zone",
    # Cardio
    "CardioSession",
    "HRZone",
    "Sex",
    "ZoneDistribution",
    "calculate_aerobic_decoupling",
    "calculate_cardiac_drift",
    "calculate_efficiency_factor",
    "calculate_gap",
    "calculate_hr_ratio",
    "calculate_trimp",
    "calculate_trimp_simplified",
    "calculate_zone_boundaries",
    "estimate_hrmax_gulati",
    "estimate_hrmax_tanaka",
    "estimate_hrmax_traditional",
    "estimate_vo2max_cooper",
    "estimate_vo2max_hr",
    "estimate_vo2max_running",
    "format_pace",
    "get_hr_zone",
    "pace_to_speed",
    "speed_to_pace",
    # Strength
    "Exercise",
    "ExerciseSet",
    "StrengthSession",
    "StrengthZone",
    "VBTZone",
    "calculate_average_intensity",
    "calculate_e1rm_volume",
    "calculate_inol",
    "calculate_relative_intensity",
    "calculate_session_inol",
    "calculate_session_volume",
    "calculate_strength_training_load",
    "calculate_volume",
    "estimate_1rm_average",
    "estimate_1rm_brzycki",
    "estimate_1rm_epley",
    "estimate_1rm_from_velocity",
    "estimate_1rm_lombardi",
    "estimate_1rm_mayhew",
    "estimate_1rm_oconner",
    "estimate_1rm_rpe",
    "get_strength_zone",
    "get_vbt_zone",
    "get_zone_boundaries",
    "percentage_from_reps",
    "velocity_target_for_percentage",
    "weight_for_reps_at_percentage",
    "weight_for_target_reps",
    # Fitness
    "DailyTSS",
    "FitnessMetrics",
    "FormZone",
    "PerformanceModel",
    "ReadinessLevel",
    "calculate_atl",
    "calculate_ctl",
    "calculate_fitness_metrics",
    "calculate_ramp_rate",
    "calculate_readiness_score",
    "calculate_tsb",
    "compute_performance_model",
    "estimate_days_to_peak",
    "get_form_zone",
    "get_readiness_level",
    "is_ramp_rate_safe",
    "predict_performance",
    "recommend_taper_duration",
    "srpe_to_tss",
    "strength_volume_to_tss",
    "trimp_to_tss",
    # Recommendations
    "Category",
    "Priority",
    "Recommendation",
    "RecommendationReport",
    "WeekPlan",
    "generate_recommendations",
    "generate_week_plan",
]
