"""AI tips endpoints: daily tips and post-session feedback.

Hybrid approach: rule-based data extraction + LLM enrichment.
Falls back to rule-based text when LLM is unavailable.
"""

from __future__ import annotations

import logging
from datetime import UTC, date, datetime, timedelta
from typing import Literal

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from arete.dataio.queries import training_loads, tss_history
from arete.dataio.settings import get_user_settings
from arete.features.fitness import compute_performance_model
from arete.features.workload import compute_workload_metrics
from arete.garmin.repository import GarminRepository
from arete.strength.repository import StrengthRepository

logger = logging.getLogger(__name__)

router = APIRouter(prefix="/tips", tags=["tips"])


# ---------- Schemas ----------
class DailyTipResponse(BaseModel):
    """Daily tip response."""

    tip: str = Field(description="Contextual training tip in French")
    priority: Literal["info", "warning", "alert"] = Field(
        description="Tip priority level"
    )
    source: Literal["llm", "rules"] = Field(
        default="rules", description="Whether tip was generated by LLM or rules"
    )
    generated_at: str = Field(description="ISO 8601 generation timestamp")


# ---------- Rule-based tip generation ----------
GOAL_ADVICE: dict[str, str] = {
    "build": "Tu peux monter de 5 à 10 % de charge cette semaine.",
    "peak": "Garde du jus : qualité plutôt que volume d'ici l'objectif.",
    "maintenance": "Tiens ce niveau, inutile d'en rajouter.",
    "recovery": "Reste en dessous du seuil : la récupération est la priorité.",
}
DEFAULT_FATIGUE_THRESHOLD = 85


def generate_daily_tip(
    acwr: float | None,
    tsb: float | None,
    readiness_score: float | None,
    fatigue_threshold: int = DEFAULT_FATIGUE_THRESHOLD,
    fitness_goal: str = "build",
) -> tuple[str, Literal["info", "warning", "alert"]]:
    """Rule-based daily tip, read against the athlete's own settings.

    Priority rules (first match wins):
    1. ACWR > 1.5 -> alert (injury danger)
    2. TSB < -25 -> alert (exhaustion)
    3. ACWR > 1.3 -> warning (overload)
    4. TSB < -10 -> warning (fatigue accumulating)
    5. readiness >= the athlete's fatigue threshold -> info (good form)
    6. ACWR 0.8-1.3 -> info (optimal zone), closed by the goal advice
    7. ACWR < 0.8 -> info (room to build), closed by the goal advice
    8. no metric at all -> info (log your sessions)

    Returns:
        (tip_text, priority)
    """
    goal_advice = GOAL_ADVICE.get(fitness_goal, GOAL_ADVICE["build"])
    if acwr is not None and acwr > 1.5:
        return (
            f"Ta charge aiguë dépasse largement la chronique (ACWR {acwr:.2f}). "
            "Réduis le volume dès aujourd'hui pour éviter la blessure.",
            "alert",
        )

    if tsb is not None and tsb < -25:
        return (
            f"Fraîcheur à {tsb:.0f} : tu es en épuisement. "
            "Prends une semaine de décharge.",
            "alert",
        )

    if acwr is not None and acwr > 1.3:
        return (
            f"Ta charge monte vite (ACWR {acwr:.2f}). "
            "Stabilise cette semaine et alterne séances dures et légères.",
            "warning",
        )

    if tsb is not None and tsb < -10:
        return (
            f"La fatigue s'accumule (fraîcheur {tsb:.0f}). "
            "Prévois une semaine de récupération bientôt.",
            "warning",
        )

    if readiness_score is not None and readiness_score >= fatigue_threshold:
        return (
            f"Préparation à {readiness_score:.0f}/100, au-dessus de ton seuil de "
            f"{fatigue_threshold}. C'est le jour pour une séance dure ou un test.",
            "info",
        )

    if acwr is not None and 0.8 <= acwr <= 1.3:
        return (
            f"Charge équilibrée (ACWR {acwr:.2f}). {goal_advice}",
            "info",
        )

    if acwr is not None and acwr < 0.8:
        return (
            f"Charge basse par rapport à tes 4 dernières semaines (ACWR {acwr:.2f}). "
            f"{goal_advice}",
            "info",
        )

    return (
        "Enregistre tes séances régulièrement pour recevoir des conseils adaptés.",
        "info",
    )


# ---------- LLM enrichment ----------

_DAILY_TIP_SYSTEM_PROMPT = """Tu es un coach sportif expert. On te donne un conseil d'entraînement basé sur des métriques réelles.

TÂCHE: Reformule ce conseil de manière naturelle, motivante et personnalisée en français.

RÈGLES:
- Garde les chiffres et métriques exacts (ACWR, TSB, etc.)
- Ajoute un conseil actionnable concret pour aujourd'hui
- Ton amical mais professionnel, tutoiement
- Maximum 3 phrases
- Ne dis jamais "en tant que coach" ou "je te conseille"
"""

_POST_SESSION_SYSTEM_PROMPT = """Tu es un coach sportif expert. On te donne un résumé de séance d'entraînement avec des métriques.

TÂCHE: Génère un feedback motivant et utile en français.

RÈGLES:
- Garde les chiffres exacts (volume, FC, allure, etc.)
- Mets en avant les points positifs
- Si nécessaire, donne 1 conseil d'amélioration
- Ton amical, tutoiement
- Maximum 3 phrases pour le feedback principal
"""


def _enrich_with_llm(system_prompt: str, rule_based_text: str) -> str | None:
    """Try to enrich rule-based text with LLM.

    Returns enriched text or None if LLM unavailable.
    """
    from arete.llm.provider import generate

    return generate(
        system_prompt,
        f"Conseil à reformuler :\n{rule_based_text}",
        temperature=0.8,
        max_tokens=300,
    )


# ---------- Endpoint: GET /tips/daily ----------
@router.get("/daily", response_model=DailyTipResponse)
def get_daily_tip() -> DailyTipResponse:
    """Get a contextual daily training tip based on current metrics."""
    target_date = date.today()

    # Fetch workload metrics
    acwr: float | None = None
    try:
        loads = training_loads(days=28)
        if any(load.duration_min > 0 for load in loads):
            workload = compute_workload_metrics(loads, target_date)
            acwr = workload.acwr
    except Exception:
        logger.warning("Failed to compute workload metrics for tip", exc_info=True)

    # Fetch fitness metrics
    tsb: float | None = None
    readiness_score: float | None = None
    try:
        tss = tss_history(days=42)
        if any(t.tss > 0 for t in tss):
            model = compute_performance_model(tss, target_date)
            tsb = model.tsb
            readiness_score = model.readiness_score
    except Exception:
        logger.warning("Failed to compute fitness metrics for tip", exc_info=True)

    # Step 1: Rule-based tip, read against the athlete's own settings
    settings = get_user_settings(user_id=1) or {}
    rule_tip, priority = generate_daily_tip(
        acwr,
        tsb,
        readiness_score,
        fatigue_threshold=int(
            settings.get("fatigue_threshold") or DEFAULT_FATIGUE_THRESHOLD
        ),
        fitness_goal=str(settings.get("fitness_goal") or "build"),
    )

    # Step 2: Try LLM enrichment
    source: Literal["llm", "rules"] = "rules"
    enriched = _enrich_with_llm(_DAILY_TIP_SYSTEM_PROMPT, rule_tip)
    if enriched:
        tip = enriched
        source = "llm"
    else:
        tip = rule_tip

    return DailyTipResponse(
        tip=tip,
        priority=priority,
        source=source,
        generated_at=datetime.now(UTC).isoformat(),
    )


# ==========================================================================
# POST /tips/post-session — Post-workout feedback
# ==========================================================================


class PostSessionRequest(BaseModel):
    """Request body for post-session feedback."""

    session_type: Literal["strength", "cardio"]
    session_id: int


class PostSessionResponse(BaseModel):
    """Post-session feedback response."""

    feedback: str = Field(description="Main feedback text in French")
    highlights: list[str] = Field(description="Key highlights in French")
    source: Literal["llm", "rules"] = Field(
        default="rules", description="Whether feedback was generated by LLM or rules"
    )


# -- Muscle group French labels --

_MUSCLE_FR: dict[str, str] = {
    "chest": "pectoraux",
    "shoulders": "épaules",
    "triceps": "triceps",
    "back": "dos",
    "biceps": "biceps",
    "forearms": "avant-bras",
    "abs": "abdominaux",
    "obliques": "obliques",
    "lower_back": "lombaires",
    "quads": "quadriceps",
    "hamstrings": "ischio-jambiers",
    "glutes": "fessiers",
    "calves": "mollets",
    "adductors": "adducteurs",
    "full_body": "corps entier",
}


def _muscle_label(key: str) -> str:
    return _MUSCLE_FR.get(key, key)


# -- HR zone helper --


def _hr_zone_label(avg_hr: int) -> tuple[int, str]:
    """Return (zone_number, zone_description) for a given avg HR."""
    if avg_hr < 120:
        return 1, "récupération active"
    if avg_hr < 140:
        return 2, "endurance fondamentale"
    if avg_hr < 155:
        return 3, "aérobie"
    if avg_hr < 170:
        return 4, "seuil"
    return 5, "VO2max"


def _pace_str(sec_per_km: float) -> str:
    """Convert seconds/km to mm:ss string."""
    minutes = int(sec_per_km) // 60
    seconds = int(sec_per_km) % 60
    return f"{minutes}:{seconds:02d}"


# -- Strength feedback --


def _generate_strength_feedback(session_id: int) -> PostSessionResponse:
    repo = StrengthRepository()
    session = repo.get_session(session_id)
    if session is None:
        raise HTTPException(status_code=404, detail="Strength session not found")

    # Compute volume per muscle for this session
    session_volume: dict[str, float] = {}
    for ex in session.exercises:
        if ex.exercise is None:
            continue
        muscle = ex.exercise.primary_muscle.value
        for s in ex.sets:
            if s.is_warmup:
                continue
            vol = (s.reps or 0) * (s.weight_kg or 0)
            session_volume[muscle] = session_volume.get(muscle, 0) + vol

    if not session_volume:
        return PostSessionResponse(
            feedback="Séance enregistrée ! Continuez à vous entraîner régulièrement.",
            highlights=["Séance complétée"],
        )

    # Compare vs last 4 weeks average
    session_date = session.date if isinstance(session.date, date) else date.today()
    end_ref = session_date - timedelta(days=1)
    start_ref = end_ref - timedelta(days=28)
    ref_volume = repo.get_volume_by_muscle(
        start_date=start_ref, end_date=end_ref, include_secondary=False
    )

    # Weeks in reference period (4)
    highlights: list[str] = []
    feedback_parts: list[str] = []

    for muscle, vol in sorted(session_volume.items(), key=lambda x: -x[1]):
        label = _muscle_label(muscle)
        ref_weekly = ref_volume.get(muscle, 0) / 4.0 if ref_volume.get(muscle) else 0

        if ref_weekly > 0:
            delta_pct = (vol - ref_weekly) / ref_weekly * 100
            if delta_pct > 5:
                highlights.append(
                    f"Volume {label} en hausse de {delta_pct:.0f}% vs les 4 dernières semaines"
                )
            elif delta_pct < -15:
                highlights.append(
                    f"Volume {label} en baisse de {abs(delta_pct):.0f}% — pensez à progresser"
                )
        else:
            highlights.append(
                f"{label.capitalize()} travaillé ({vol:.0f} kg de volume)"
            )

    total_vol = sum(session_volume.values())
    muscles_worked = [_muscle_label(m) for m in session_volume]
    feedback_parts.append(
        f"Séance musculation terminée — {total_vol:.0f} kg de volume total "
        f"sur {', '.join(muscles_worked)}."
    )

    if session.overall_rpe:
        feedback_parts.append(f"RPE ressenti : {session.overall_rpe}/10.")

    if not highlights:
        highlights.append("Séance complétée avec succès")

    rule_feedback = " ".join(feedback_parts)
    rule_highlights = highlights[:5]

    # Try LLM enrichment on the feedback text
    source: Literal["llm", "rules"] = "rules"
    enriched = _enrich_with_llm(
        _POST_SESSION_SYSTEM_PROMPT,
        f"{rule_feedback}\n\nPoints clés:\n"
        + "\n".join(f"- {h}" for h in rule_highlights),
    )
    if enriched:
        rule_feedback = enriched
        source = "llm"

    return PostSessionResponse(
        feedback=rule_feedback,
        highlights=rule_highlights,
        source=source,
    )


# -- Cardio feedback --


def _generate_cardio_feedback(session_id: int) -> PostSessionResponse:
    repo = GarminRepository()
    session = repo.get_actual_session(session_id)
    if session is None:
        raise HTTPException(status_code=404, detail="Cardio session not found")

    highlights: list[str] = []
    feedback_parts: list[str] = []

    sport = session.sport or "activité"
    duration_min = (session.duration_sec or 0) // 60

    feedback_parts.append(f"Séance de {sport} terminée ({duration_min} min).")

    # HR feedback
    if session.avg_hr and session.max_hr:
        zone_num, zone_desc = _hr_zone_label(int(session.avg_hr))
        highlights.append(
            f"FC moyenne à {session.avg_hr:.0f} bpm, zone {zone_num} {zone_desc}"
        )
        highlights.append(f"FC max à {session.max_hr:.0f} bpm")

        if zone_num <= 2:
            feedback_parts.append("Bon travail de fond, intensité bien maîtrisée.")
        elif zone_num == 3:
            feedback_parts.append("Bon travail de fond en zone aérobie.")
        elif zone_num >= 4:
            feedback_parts.append("Séance intense — prévoyez une récupération adaptée.")

    # Pace feedback
    if session.avg_pace_sec_km and session.avg_pace_sec_km > 0:
        pace = _pace_str(session.avg_pace_sec_km)
        highlights.append(f"Allure moyenne : {pace} /km")

    # Distance
    if session.distance_m and session.distance_m > 0:
        km = session.distance_m / 1000
        highlights.append(f"Distance : {km:.1f} km")

    # Calories
    if session.calories and session.calories > 0:
        highlights.append(f"{session.calories} kcal dépensées")

    if not highlights:
        feedback_parts.append("Continuez à vous entraîner régulièrement.")
        highlights.append("Séance complétée")

    rule_feedback = " ".join(feedback_parts)
    rule_highlights = highlights[:5]

    # Try LLM enrichment
    source: Literal["llm", "rules"] = "rules"
    enriched = _enrich_with_llm(
        _POST_SESSION_SYSTEM_PROMPT,
        f"{rule_feedback}\n\nPoints clés:\n"
        + "\n".join(f"- {h}" for h in rule_highlights),
    )
    if enriched:
        rule_feedback = enriched
        source = "llm"

    return PostSessionResponse(
        feedback=rule_feedback,
        highlights=rule_highlights,
        source=source,
    )


# -- Endpoint --


@router.post("/post-session", response_model=PostSessionResponse)
def post_session_feedback(body: PostSessionRequest) -> PostSessionResponse:
    """Generate post-workout feedback with optional LLM enrichment."""
    if body.session_type == "strength":
        return _generate_strength_feedback(body.session_id)
    else:
        return _generate_cardio_feedback(body.session_id)
