/** Questions offered to the athlete, fixed per page.
 *
 *  They used to be generated by one more model request after every answer,
 *  which held the "done" event for up to eight seconds and spent a request of
 *  a 50-a-day free quota. A question that fits the open page is as useful. */

const GENERAL = [
  'Que peux-tu faire pour moi ?',
  'Analyse ma forme du moment',
  'Aide-moi à planifier ma semaine',
];

const BY_PAGE: Record<string, string[]> = {
  dashboard: [
    "Que dois-je faire aujourd'hui ?",
    'Comment est ma récupération ?',
    'Résume ma semaine',
  ],
  planning: [
    'Ma semaine est-elle bien équilibrée ?',
    'Allège ma semaine, je suis fatigué',
    'Ajoute une sortie longue ce week-end',
  ],
  analytics: [
    'Compare ma charge sur 7 et 28 jours',
    'Mon allure progresse-t-elle ?',
    'Où en est ma forme sur 6 semaines ?',
  ],
  log: [
    'Que retiens-tu de ma dernière séance ?',
    'Mes séances récentes sont-elles trop intenses ?',
    'Je veux enregistrer une séance de musculation',
  ],
  profile: [
    'Explique ma progression et mes Éclats',
    'Quel est mon prochain rang ?',
    'Comment respecter mon objectif cette semaine ?',
  ],
  settings: [
    'Mes zones cardiaques sont-elles à jour ?',
    'Explique-moi mon seuil',
    'Que peux-tu faire pour moi ?',
  ],
};

/** Opening questions for an empty thread. */
export function starters(page: string): string[] {
  return BY_PAGE[page] ?? GENERAL;
}

/** Up to three questions for after an answer, never one already asked. */
export function followUps(page: string, asked: string[]): string[] {
  const seen = new Set(asked.map((q) => q.trim().toLocaleLowerCase()));
  return [...new Set([...starters(page), ...GENERAL])]
    .filter((q) => !seen.has(q.toLocaleLowerCase()))
    .slice(0, 3);
}
